/**
 * @description define the navigation routes name by key
 */
export enum Routes {
  Login = 'Login',
  Register = 'Register',
  Intro = 'Intro',
  HomeTabs = 'HomeTabs',
  Profile = 'Profile',
  Home = 'Home',
  Account = 'Account',
  Statistic = 'Statistic',
  Transaction = 'Transaction',
  OTP = 'OTP',
  KYC = 'KYC',
  ResetPassword = 'ResetPassword',
  InputPassword = 'InputPassword',
  ResearchFn = 'ResearchFn',
  ListDriver = 'ListDriver',
  GroupDriverDetail = 'GroupDriverDetail',
  DriverCustom = 'DriverCustom',
  Accessories = 'Accessories',
  ProductDetail = 'ProductDetail',
  Address = 'Address',
  PickAddress = 'PickAddress',
  BookAddress = 'BookAddress',
  ChangePassword = 'ChangePassword',
  InfoAccount = 'InfoAccount',
  Policy = 'Policy',
  RequestDelete = 'RequestDelete',
  Term = 'Term',
  News = 'News',
  BuySellExchange = 'BuySellExchange',
  CategoryNews = 'CategoryNews',
  DetailNews = 'DetailNews',
  OrderPart = 'OrderPart',
  HistoryOrders = 'HistoryOrders',
  OrderDetail = 'OrderDetail',
  Feedback = 'Feedback',
  DetailAddress = 'DetailAddress',
  Cart = 'Cart',
  CartOrder = 'CartOrder',
  Search = 'Search',
  SearchResult = 'SearchResult',
  Category = 'Category',
  Product = 'Product',
  Branch = 'Branch',
  Notification = 'Notification',
  HistoryOrderDetail = 'HistoryOrderDetail',
  Contact = 'Contact',
  Support = 'Support',
}
